language: node_js
node_js:
  - '8'
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app:
    develop: is2-authentication-develop
before_install:
  - npm install dredd@5.2.0 --no-optional --global
install:
  - "npm install --no-optional"
before_script:
  - "npm info dredd version"
  - dredd